---
# tasks file for os_keystone_manipulate
    - name: keystone service start
      service: name=keystone state=started 
          
    - name: Keystone service create with cli
      command: openstack service create --name keystone --description "OpenStack Identity" identity
      environment:
       - OS_TOKEN: "{{ ADMIN_TOKEN }}" 
         OS_URL: "{{ OS_URL }}"
         OS_IDENTITY_API_VERSION: "{{ OS_IDENTITY_API_VERSION }}"
      register: command_result
      #failed_when: "'two projects acting as domains with the same name' not in command_result.stderr and command_result.stderr != ''"
      #with_items: "{{ keystone_domains }}" 
      tags: key_service
