---
# tasks file for os_keystone_manipulate
    - name:         keystone service start
      service:      name=keystone state=restarted 
          
    - name:         Get list of services.
      changed_when: no
      command:      openstack service list -f value -c Type
      register:     openstack_services
      
    - name:         Keystone service create with cli
      command:      openstack service create --name keystone --description "OpenStack Identity" identity
      when:         '"identity" not in openstack_services.stdout'
      tags:         key_service
    
    - name:         Get list of endpoints
      changed_when: no
      command:      openstack endpoint list -f value -c "Service Name"
      register:     openstack_endpoints
      
    - name:         Endpoint create
      command:      openstack endpoint create --region RegionOne identity {{ item.name }} http://controller:{{ item.port }}/v3
      with_items: 
        - name: public
          port: 5000 
        - name: admin
          port: 35357
        - name: internal
          port: 5000
      when:         '"{{item.name}}" not in openstack_endpoints.stdout'
      tags:         endpoint_create
      
    - name:         Get list of domains.
      changed_when: no
      command:      openstack domain list -f value -c Name
      register:     openstack_domains
    
    
    - name:         Domain create
      command:      openstack domain create --description "Default Domain" default
      when:         '"default" not in openstack_domains.stdout'
      tags:         domain_create
    
    - name:         Get list of projects.
      register:     openstack_projects
      changed_when: no
      command:      openstack project list -f value -c Name --domain default

    
    - name:         Create projects.
      command:      'openstack project create --domain default --description "{{ item.description }}" {{ item.name }}'
      when:         '"{{ item.name }}" not in "{{openstack_projects.stdout}}"'
      with_items:
        - name:        admin
          description: Admin Project

        - name:        service
          description: Service Project

        - name:        demo
          description: Demo Project
   
    - name:         Get list of users.
      register:     openstack_users
      changed_when: no
      command:      openstack user list -f value -c Name --domain default

    - name:    Create users.
      command: 'openstack user create --domain default --password {{ item.password }} {{ item.name }}'
      when:    '"{{ item.name }}" not in openstack_users.stdout'
      with_items:
    
        - name: admin
          password: '{{ admin_password }}'

        - name: demo
          password: '{{ demo_password }}'
      
    - name:         Get list of roles.
      register:     openstack_roles
      changed_when: no
      command:      openstack role list -f value -c Name

    - name:    Create roles.
      command: 'openstack role create {{ item }}'
      when:    '"{{ item }}" not in openstack_roles.stdout'
      with_items:
        - admin
        - user

    - name:         Assign roles.
      changed_when: no
      command:      'openstack role add --project {{ item.project }} --user {{ item.user }} {{ item.role }}'
      with_items:
        - project: admin
          user:    admin
          role:    admin

        - project: demo
          user:    demo
          role:    user  
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
