---
# handlers file for os_common
- name: chrony restart
  service: name=chrony state=restarted

- name: networking
  service: name=networking state=restarted

- name: mysqld_reload
  service: name=mysql state=restarted
  
- name: sites-enabled
  file: src=/etc/apache2/sites-available/wsgi-keystone.conf dest=/etc/apache2/sites-enabled state=link
