---
# tasks file for os_controller
    - name: hostame
      hostname: name=controller

    - name: Install controller's software
      apt: name={{item}} state=present update_cache=yes install_recommends=yes force=yes
      with_items :  
          - mariadb-server 
          - python-pymysql
          - rabbitmq-server
          - keystone
          - python-openstackclient
          - apache2
          - libapache2-mod-wsgi
          - memcached
          - python-memcache
          - python-mysqldb
      tags: controller_packages
           
    - name: Stop mysql service  
      service: name=mysql state=stopped
   
    - name: Create config for mysql
      template: src=control_mysql.conf.j2 dest=/etc/mysql/conf.d/openstack.cnf owner=root group=root mode=0644
      tags: mysql_config
    
    - name: Search old InnoDB log files
      find: paths="/var/lib/mysql/" patterns="ib_logfile*"
      register: logs
      tags: search_log
    
    - name: Remove old InnoDB log files
      file: path=/var/lib/mysql/{{ item }} state=absent
      with_items: 
        - ib_logfile0
        - ib_logfile1
      tags: rem_log
    
    - name: Start mysql service  
      service: name=mysql state=started
        
    - name: Create rabbit user with full privileges  
      rabbitmq_user: user=openstack
                     password={{RABBIT_PASS}}
                     vhost=/
                     configure_priv=.*
                     read_priv=.*
                     write_priv=.*
                     state=present
    
    - name: Configure memcached listen iface
      template: src=memcache.conf.j2 dest=/etc/memcached.conf owner=root group=root mode=0644
      tags: memcached_config
    
    - name: Restart memcached service  
      service: name=memcached state=restarted  
      tags: memcached_restart
    
    - name: Catch keystone status
      register: keystone_status
      command: service keystone status 
    
    - debug: msg="Keystone service are {{keystone_status}}"
    
    - name: Create config for keystone
      template: src=keystone.conf.j2 dest=/etc/keystone/keystone.conf owner=root group=root mode=0644
      tags: keystone_config

    - name: Create DB keystone
      mysql_db: name=keystone state=present
      tags: db_create
    
    - name: Create keystone DB user
      mysql_user: name=keystone password={{KEYSTONE_DBPASS}} priv=keystone.*:ALL state=present check_implicit_admin=yes  host={{item}}
      with_items:
        - '%'
        - localhost
      tags: dbuser_create   
      
    - name: Disable autostart of keystone service in sysinit
      lineinfile: dest=/etc/init/keystone.override line="manual" state=present create=yes
      tags: keystone_manual_start
    
    - name: Populate keystone DB
      raw: su -s /bin/sh -c "keystone-manage db_sync" keystone
      tags: keystone_db_populate
  
    - name: Enable fernet keys
      raw:  keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
      tags: fernet
        
    - name: Apache2 servername
      lineinfile: dest=/etc/apache2/apache2.conf line="ServerName controller" state=present create=yes
      tags: apache2_servername
      
    - name: Apache conf for keystone
      copy: src=wsgi-keystone.conf dest=/etc/apache2/sites-available/wsgi-keystone.conf 
      tags: apache2_config
      notify:
        - sites-enabled
    
    - name: Admin rc script
      template: src=openrc.j2 dest=/root/openrc owner=root group=root mode=0644
